[bar/main]
width = 100%
height = 14 
padding = 1
module-margin = 0
; background = #1e1e2e

background = #000000
foreground = #cdd6f4
font-0 = JetBrainsMono Nerd Font:size=10;2

modules-left = i3
modules-center = xwindow
modules-right = pulseaudio memory date

separator = |
separator-foreground = #585b70

;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;   MÓDULOS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[module/i3]
type = internal/i3
format = <label-state>
pin-workspaces = false
;label-separator = " "

;Esta es la mia
; Estado activo
label-focused = ●
label-focused-foreground = #cad3f5
label-focused-padding = 1
label-focused-underline = #cad3f5

; Estado inactivo
label-unfocused = ○
label-unfocused-foreground = #E0E0E0 
label-unfocused-padding = 1


; Otros estados
label-visible = ○
label-visible-padding = 1
label-urgent = ⚠
label-urgent-padding = 1
label-urgent-underline = #f38ba8 

; Tu me diste esta
[module/cpu]
type = internal/cpu
interval = 2
label =  %percentage%%
label-padding = 2


[module/xwindow]
type = internal/xwindow
label = %title:0:50:...%

[module/memory]
type = internal/memory
interval = 2
label =  %used% / %total%
label-padding = 2

[module/wlan]
type = internal/network
interface = wlp4s0
interval = 3
label-connected =  %essid% %downspeed%
label-disconnected = 睊 Offline
label-padding = 2

[module/eth]
type = internal/network
interface = enp5s0
interval = 3
label-connected =  %local_ip%
label-disconnected =  Down
label-padding = 2

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 98
label-charging =  %percentage%%
label-discharging =  %percentage%%
label-full =  100%
label-padding = 2

[module/date]
type = internal/date
interval = 60
#date = %a %d %b %H:%M
date = %H:%M
label =  %date%
label-padding = 2

[module/pulseaudio]
type = internal/pulseaudio

; Formato general (qué mostrar)
format-volume = <label-volume>

; Texto cuando hay audio
label-volume =  %percentage%%
label-volume-padding = 2

; Texto cuando está muteado
label-muted =  muted
label-muted-foreground = #f38ba8

